### ISSUE TITLE
Re "close developer relationships" misleading statement

### ISSUE THREAD

**Issue by grctest** [bitshares/Roadmap#2]
> Relationships: We believe in close working relationships with developers and organizations that build on and contribute to the BitShares Blockchain.

So why ban them for petty personal reasons?

It seems like you're saying one thing to attract investors here but in reality act completely differently in practice, quite misleading.

Time for a code of conduct to avoid tinpot dictators degrading Bitshares future?  At least for the purpose of preventing repeated implicit death threats towards developers whom you don't like should be a minimum bar of conduct for a committee member (even one with as little as 0.04% support...)

> BitShares Group is at the heart of this: we need to not just serve the BitShares Blockchain community, but work with them and incorporate their feedback.

This seems fairly inaccurate; You ban those who provide negative feedback.

**Comment by ioBanker** [comment]
> So why ban them for petty personal reasons?

I'd banned you from my own Telegram groups which I found myself; hence I have the full rights to use my own authority right there, you can create your own Telegram Groups if you don't like what is happening in my groups, anyway the reason behind your ban is for leaving my own groups then monitoring and trashing the posts within the group with your bad expressions; I am sure that you have done so as a response to your own failure as a developer to convince BitShares investors to fund your developments; you'd decided to attack news post on my own telegram groups and then trying to convince others in groups and GitHub that BitShares has a wrong direction.

> This seems fairly inaccurate; You ban those who provide negative feedback.

You haven't provided a negative feedback; see above.

**Comment by grctest** [comment]
> trashing the posts within the group with your bad expression

Read: Banned for using a single emoji reaction on a CMC conspiracy theory post I deemed exceedingly low quality - emojis which you allowed in your telegram channel as reactions to your content.

The emoji in question? 💩

That is in fact negative feedback, deal with it.

The fact is the roadmap contains misinformation to mislead investors. Act differently if this roadmap is the reality you want.

> I am sure that you have done so as a response to your own failure as a developer to convince BitShares investors to fund your developments; you'd decided to attack news post on my own telegram groups and then trying to convince others in groups and GitHub that BitShares has a wrong direction.

Nope, it's because the CMC post was nonsense. We shouldn't be fighting govts proposing the use of technology which bitshares offers as core functionality.

Trying to convince others that the current direction BTS is taking is a ban worthy offence? You're severely delusional and I'm taking your repeated implicit death threats seriously.

You even banned me from the dev channel despite the emoji response occurring in another channel, a purely retaliatory action designed to sever my connections from the other bitshares developers. All telegram groups you administrate now have zero legitimacy.

**Comment by grctest** [comment]
Yeesh, how can you be a proponent for closer developer relations now that you're an outspoken proponent for a well known hate organization on telegram?

Frankly you should seek immediate mental health assistance before you cause harm to yourself or others around you.
