### ISSUE TITLE
Re Trust

### ISSUE THREAD

**Issue by grctest** [bitshares/Roadmap#3]
> BitShares Group culture and core principles
> Trust: We believe trust is foundational to our mission and building trust is a slow, steady process. Trust is hard-earned and easily lost.

How can this be an advertised core principal of the Bitshares Group when implicit death threats are sent to those you disagree with? How can you expect to ever be trusted when you demonstrate such evil intent and callous disregard of the health of your developers?

You're right that trust is hard-earned, you've only achieved 0.04% of the total supply to elect you as an active committee member; 99.96% don't trust you with the role.

Easily lost? Yeah, about $15k could push you out of the committee entirely.

**Comment by ioBanker** [comment]
> How can this be an advertised core principal of the Bitshares Group when implicit death threats are sent to those you disagree with? How can you expect to ever be trusted when you demonstrate such evil intent and callous disregard of the health of your developers?

Never happened; you are an anonymous freelancer, not even a member of our official GitHub development team who'd failed to convince BitShares investors over Telegram *unrelated to GitHub* to fund your personal development direction while here attacking my identity with false claims, this issue has been reported to *GitHub* and *BitShares GitHub Page owner* privately for the reference.

**Comment by grctest** [comment]
> Never happened

I disagree.

> false claims

That's not how I perceived your historical communications.

> you are an anonymous freelancer

So what? Irrelevant. I perceive the roadmap as currently misleading to investors, hence the issue.

>  not even a member of our official GitHub development team

Not part of the github org despite a forked repo in the bitshares org, no. But listed as a core js dev on the website.

> personal development direction

Good enough to show off to binance in the q&a though

> while here

Nope. These communications are occurring several months after I ceased seeking development funding. Get your facts straight.

> attacking my identity

Hardly.

Some would point out that a fundamental part of delegated proof of stake is to communicate openly regarding perceived negatives associated with elected officials, it's an active democracy after all, even if DPOS campaigning activity is low. If you can't handle the negatives associated with DPOS then maybe you're not up for the job?

I could easily perceive the same in return as this line re trust being easily lost seems like you laying down your own laws re cutting people out of the community in a manner not in line with the [code of conduct](https://github.com/bitshares/bitshares-ui/blob/develop/CODE_OF_CONDUCT.md) around about when you did so.

> this issue has been reported to GitHub and BitShares GitHub Page owner privately for the reference.

Good, following the process laid out in the [code of conduct](https://github.com/bitshares/bitshares-ui/blob/develop/CODE_OF_CONDUCT.md) is imperative.

**Comment by grctest** [comment]
How can you be trusted given that you dish out bans to anyone who upsets you?

Frankly, I found your comments of support towards a known hatred organization on telegram to be highly alarming. With that in mind, how can anyone trust what you write about Bitshares?

Note that these issues weren't deleted a whole year later, because they're accurate claims.

Actual nonsense.
